# Generated by Django 5.2.17 on 2026-09-12 23:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('math', 'Math'), ('tech', 'Tech'), ('music', 'Music'), ('other', 'Other')], default='tech', max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
