# Generated by Django 5.2.17 on 2026-09-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
