# Generated by Django 5.2.17 on 2026-09-19 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('math', 'Math'), ('tech', 'Tech'), ('music', 'Music'), ('random', 'Random'), ('other', 'Other')], default='tech', max_length=20)),
                ('read_time', models.CharField(max_length=255)),
            ],
        ),
    ]
