# Generated by Django 5.2.17 on 2026-09-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
